site_name: nixnotes
theme:
  name: material
  features:
    - content.code.annotate  # Подсветка кода
    - navigation.tabs
plugins:
  - git-revision-date
markdown_extensions:
  - toc:
      permalink: true
  - codehilite
nav:
  - Home: index.md
  - Base coommands: com.md
  - Docker steps: Docker.md